### ISSUE TITLE
Some missing requirements

### ISSUE THREAD

**Issue by axeberg** [chas-academy/k02-php-oop-jquery-Jonon#1]
Great job @Jonon - if you can fix the stuff below I'm okay with passing this assignment:

- [x] Webbplatsen ska ha en design kopplad till Personas och Scenarios ~och nyttja Bootstrap för implementation~
- [x]  Webbplatsen ska följa teknisk [Teknisk kravspecifikation för k02](https://www.notion.so/243cad95-cdcf-4356-a641-1a9ab076500c) endast punkter nedan saknas
    - [x] 5.  A user **must** be able to follow other users and vice versa
    - [x] **Sitemap**
    - [x] **User Personas & Stories**

**Comment by Jonon** [comment]
@axelolsson The issue with missing requirements should be fixed. If you look in the readme, you can see that I have provided some links.

**Comment by axeberg** [comment]
@Jonon behöver minst tre Personas om jag inte sagt något annat i kravspecen. Sedan är denna klar!

**Comment by Jonon** [comment]
@axelolsson fixat!

**Comment by axeberg** [comment]
@Jonon grymt, då släcker vi denna.

Du är betygssatt nu.
